# Generated by Django 3.2.5 on 2021-07-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название устройства')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес размещения')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Долгота')),
                ('radius', models.IntegerField(default=0, verbose_name='Радиус зоны звукопокрытия')),
                ('category', models.CharField(choices=[('Сирена', 'Сирена'), ('Громкоговоритель', 'Громкоговоритель')], max_length=50, verbose_name='Тип устройства')),
            ],
        ),
    ]
