# Generated by Django 3.2.5 on 2021-07-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['title'], 'verbose_name': 'Устройствa', 'verbose_name_plural': 'Устройств'},
        ),
    ]
