# Generated by Django 3.2.5 on 2021-07-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Устройствa', 'verbose_name_plural': 'Устройств'},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='address',
            new_name='location_address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='radius',
            new_name='zone_radius',
        ),
    ]
